### ISSUE TITLE
Vici not seeded with er-dummy repository at startup

### ISSUE THREAD

**Issue by emichaf** [eiffel-community/eiffel-easy2use#3]
Vici not seeded with er-dummy repository at startup

**Comment by pef-ericsson** [comment]
@e-backmark-ericsson @m-linner-ericsson
I have done an investigation on Kubernetes cluster. 

It seems that **dummy-er-<_namespace_>-0** pod does not start properly. Actually, there is the following error _"cat: /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes: No such file or directory"_. The error perhaps is related to **cgroup v2** incompatibility due to **JDK version**. 
The error leads to _"java.io.FileNotFoundException"_ trying to download Eiffel events from the local file and then to _"java.lang.NullPointerException: null"_ trying to get the events in **eiffel-vici-<_namespace_>-0** pod.

Moreover, **dummy-er** visualizes Eiffel events fetching them from a provided preferred URL as a JSON file, see (https://github.com/eiffel-community/eiffel-vici/blob/master/src/main/java/com/ericsson/vici/Fetcher.java#L143). That means that Vici does not fetch Eiffel events from _Eiffel-ER or RabbitMQ (MessageBus)_.

**Comment by e-backmark-ericsson** [comment]
Maybe we shouldn't try to solve the issue using dummy ER, but instead using a "real" ER, as noted in this issue: https://github.com/eiffel-community/eiffel-vici/issues/37 ?

Also, [Eiffel Store](https://github.com/eiffel-community/eiffel-store) is a fork of Vici, which is said to add the possibility to visualize live data from MB in the gui. The Eiffel Store might be more up to date with recent fixes, since it was updated more recently than Vici. You could also discuss the issue with the contributors on Eiffel Store to see if they've seen similar issues in Eiffel Store as you've seen in Vici.

**Comment by pef-ericsson** [comment]
1. I agree that we shouldn't try fixing the **dummy-er**.
2. We can check if it's feasible to use [eiffel-store.](https://github.com/eiffel-community/eiffel-store)
